defaults:
  -
    scope:
      path: ""

    values:
      layout: "default"
      title: "TransitData API"
      github_org_title: "TransitData"
      github_org_url: "https://github.com/TransitData"
